# Generated by Django 5.2.10 on 2026-02-07 07:52

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(blank=True, help_text='Write a title for the about section', max_length=255, verbose_name='About Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email_signup_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email_signup_title',
            field=models.CharField(blank=True, help_text='Write a title for the email signup', max_length=255, verbose_name='Email Signup Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_header',
            field=models.CharField(blank=True, help_text='Write a header for the hero section', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_cta',
            field=models.CharField(blank=True, help_text='Text to display on Call to Action', max_length=255, verbose_name='Hero Primary CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero Primary CTA link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_cta',
            field=models.CharField(blank=True, help_text='Text to display on Call to Action', max_length=255, verbose_name='Hero Secondary CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Secondary Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero Secondary CTA link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subheader',
            field=models.CharField(blank=True, help_text='Write a short blurb for the hero section', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
