# Generated by Django 5.2.10 on 2026-02-19 08:07

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_about_content_homepage_about_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='site_intro',
            new_name='budget_meals_content',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_subheader',
            new_name='hero_subtitle',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_header',
            new_name='hero_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='budget_meals_cta_text',
            field=models.CharField(blank=True, help_text='Call to action link text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='budget_meals_title',
            field=models.CharField(blank=True, help_text='Budget Meals Title', max_length=255, verbose_name='Budget Meals Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email_signup_button_text',
            field=models.CharField(blank=True, help_text='Button text for email signup'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_recipes_intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_recipes_title',
            field=models.CharField(blank=True, help_text='Featured Recipes Title', max_length=255, verbose_name='Featured Recipes title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='highlights_first_feature_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='highlights_first_feature_title',
            field=models.CharField(blank=True, help_text='First feature title', verbose_name='First Feature Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='highlights_intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='highlights_second_feature_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='highlights_second_feature_title',
            field=models.CharField(blank=True, help_text='Second feature title', verbose_name='Second Feature Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='highlights_third_feature_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='highlights_third_feature_title',
            field=models.CharField(blank=True, help_text='Third feature title', verbose_name='Third Feature Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='highlights_title',
            field=models.CharField(blank=True, help_text='Text to display in the highlight section title', max_length=255, verbose_name='Highlights section title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='philosophy_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='philosophy_title',
            field=models.CharField(blank=True, help_text='Title to highlight our approach', max_length=255, verbose_name='Philosophy Title'),
        ),
    ]
