# Generated by Django 5.2.10 on 2026-06-28 09:06

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_site_intro_homepage_budget_meals_content_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Text to display on Call to Action', max_length=255, null=True, verbose_name='Call to action text')),
                ('link', models.ForeignKey(blank=True, help_text='Choose a page to link to for the Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero Primary CTA link')),
            ],
        ),
        migrations.CreateModel(
            name='HowItWorksItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ValueBarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='budget_meals_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='budget_meals_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='budget_meals_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_recipes_intro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_recipes_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_primary_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_primary_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_secondary_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_secondary_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='highlights_first_feature_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='highlights_first_feature_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='highlights_intro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='highlights_second_feature_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='highlights_second_feature_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='highlights_third_feature_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='highlights_third_feature_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='highlights_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='philosophy_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='philosophy_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_it_works_text',
            field=models.CharField(blank=True, help_text='Short description for how it works', max_length=255, null=True, verbose_name='How it works description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_it_works_title',
            field=models.CharField(blank=True, help_text='Title text for how it works', max_length=255, null=True, verbose_name='How it works title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(blank=True, help_text='Write a title for the about section', max_length=255, null=True, verbose_name='About Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='email_signup_button_text',
            field=models.CharField(blank=True, help_text='Button text for email signup', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='email_signup_title',
            field=models.CharField(blank=True, help_text='Write a title for the email signup', max_length=255, null=True, verbose_name='Email Signup Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Write a short blurb for the hero section', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Write a header for the hero section', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='HomePageHowItWorksItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_it_works_list', to='home.homepage')),
                ('how_it_works_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.howitworksitem')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageValueBarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_value_bar', to='home.homepage')),
                ('value_bar_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.valuebaritem')),
            ],
        ),
        migrations.CreateModel(
            name='AboutCTA',
            fields=[
                ('cta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.cta')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_cta', to='home.homepage')),
            ],
            bases=('home.cta',),
        ),
        migrations.CreateModel(
            name='HeroCTA',
            fields=[
                ('cta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.cta')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_cta', to='home.homepage')),
            ],
            bases=('home.cta',),
        ),
        migrations.CreateModel(
            name='HowItWorksCTA',
            fields=[
                ('cta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.cta')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_it_works_cta', to='home.homepage')),
            ],
            bases=('home.cta',),
        ),
    ]
