# Generated by Django 5.2.10 on 2026-02-11 08:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RecipesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('category', models.CharField(blank=True, help_text='Recipe Category', max_length=255)),
                ('cook_time', models.CharField(blank=True, help_text='Recipe Cook Time', max_length=255)),
                ('calories', models.CharField(blank=True, help_text='Recipe Calories', max_length=255)),
                ('servings', models.CharField(blank=True, help_text='Recipe Cook Time', max_length=255)),
                ('nutrition', wagtail.fields.RichTextField(blank=True)),
                ('ingredients', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('notes', wagtail.fields.RichTextField(blank=True)),
                ('main_image', models.ForeignKey(blank=True, help_text='Recipe Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('secondary_image', models.ForeignKey(blank=True, help_text='Recipe Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
