# Generated by Django 5.2.10 on 2026-02-24 14:06

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='RecipesIndexPage',
            new_name='RecipeIndexPage',
        ),
        migrations.CreateModel(
            name='RecipePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('meta_description', models.CharField(blank=True, help_text='Shown in Google results', max_length=160)),
                ('focus_keyword', models.CharField(blank=True, help_text='Primary SEO keyword', max_length=100)),
                ('description', models.TextField()),
                ('prep_time', models.PositiveIntegerField(help_text='Minutes')),
                ('cook_time', models.PositiveIntegerField(help_text='Minutes')),
                ('total_time', models.PositiveIntegerField(help_text='Prep + Cook (minutes)')),
                ('servings', models.PositiveIntegerField()),
                ('cost_per_serving', models.DecimalField(blank=True, decimal_places=2, help_text='USD cost per serving', max_digits=5, null=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('protein', models.PositiveIntegerField(blank=True, null=True)),
                ('carbs', models.PositiveIntegerField(blank=True, null=True)),
                ('fat', models.PositiveIntegerField(blank=True, null=True)),
                ('cuisine', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(default='Dinner', max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('affiliate_product', models.URLField(blank=True, help_text='Primary affiliate link (tool/ingredient)')),
                ('sponsored', models.BooleanField(default=False)),
                ('lead_magnet_cta', models.CharField(blank=True, default='Get My Free Budget Meal Plan', max_length=100)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(help_text='e.g. 1 cup, 200g, 2 tbsp', max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipepage')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('instruction', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipepage')),
            ],
        ),
        migrations.DeleteModel(
            name='RecipesPage',
        ),
    ]
