# Generated by Django 5.2.10 on 2026-05-10 08:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_rename_recipesindexpage_recipeindexpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredients',
            field=wagtail.fields.StreamField([('ingredient_list', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Ingredient Amount', 'help_text': 'e.g. 1 cup or 200g', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Ingredient Name', 'help_text': 'e.g. All-purpose flour', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('amount', 0), ('name', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})}, default='ingredient'),
            preserve_default=False,
        ),
    ]
