# Generated by Django 5.2.10 on 2026-05-10 23:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeingredient_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='ingredients',
            field=wagtail.fields.StreamField([('ingredients', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 1 cup or 200g', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. All-purpose flour', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('amount', 0), ('name', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})}, default='default'),
            preserve_default=False,
        ),
    ]
