# Generated by Django 5.2.10 on 2026-05-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipepage_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepage',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
