# Generated by Django 5.2.10 on 2026-05-29 00:59

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(help_text='e.g., mg, g, mcg', max_length=10)),
            ],
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='IngredientNutrientRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('ingredient', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_nutrients', to='recipes.ingredient')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipes.nutrient')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
