# Generated by Django 5.2.10 on 2026-05-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_nutrient_ingredientnutrientrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='serving_size_unit',
            field=models.CharField(default='', max_length=100),
        ),
    ]
