# Generated by Django 5.2.10 on 2026-05-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_nutrient_serving_size_nutrient_serving_size_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='serving_size',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='serving_size_unit',
        ),
    ]
