# Generated by Django 5.2.10 on 2026-05-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_nutrient_serving_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientnutrientrelationship',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
