# Generated by Django 5.2.10 on 2026-05-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_ingredientnutrientrelationship_serving_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientnutrientrelationship',
            name='serving_size',
        ),
    ]
