# Generated by Django 5.2.10 on 2026-05-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_remove_ingredientnutrientrelationship_serving_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientnutrientrelationship',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
