# Generated by Django 5.2.10 on 2026-05-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_ingredientnutrientrelationship_serving_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='note',
            field=models.CharField(blank=True, help_text="e.g. chopped, sifted, divided, or 'to taste' if qty is empty", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('ml', 'Milliliters (ml)'), ('l', 'Liters (l)'), ('tsp', 'Teaspoons (tsp)'), ('tbsp', 'Tablespoons (tbsp)'), ('cup', 'Cups'), ('fl_oz', 'Fluid Ounces (fl oz)'), ('g', 'Grams (g)'), ('kg', 'Kilograms (kg)'), ('oz', 'Ounces (oz)'), ('lb', 'Pounds (lb)'), ('piece', 'Piece(s)'), ('can', 'Can(s)'), ('pinch', 'Pinch(es)'), ('clove', 'Clove(s)'), ('head', 'Head(s)')], help_text='Standardized unit of measurement', max_length=20, null=True),
        ),
    ]
