# Generated by Django 5.2.10 on 2026-06-13 08:37

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_remove_recipeingredient_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='category',
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='unit',
            field=models.CharField(blank=True, choices=[('ml', 'Milliliters (ml)'), ('l', 'Liters (l)'), ('tsp', 'Teaspoons (tsp)'), ('tbsp', 'Tablespoons (tbsp)'), ('cup', 'Cups'), ('fl_oz', 'Fluid Ounces (fl oz)'), ('g', 'Grams (g)'), ('mg', 'Milligrams (mg)'), ('mcg', 'Micrograms (mcg)'), ('kg', 'Kilograms (kg)'), ('oz', 'Ounces (oz)'), ('lb', 'Pounds (lb)'), ('piece', 'Piece(s)'), ('can', 'Can(s)'), ('pinch', 'Pinch(es)'), ('clove', 'Clove(s)'), ('head', 'Head(s)')], help_text='Standardized unit of measurement', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('ml', 'Milliliters (ml)'), ('l', 'Liters (l)'), ('tsp', 'Teaspoons (tsp)'), ('tbsp', 'Tablespoons (tbsp)'), ('cup', 'Cups'), ('fl_oz', 'Fluid Ounces (fl oz)'), ('g', 'Grams (g)'), ('mg', 'Milligrams (mg)'), ('mcg', 'Micrograms (mcg)'), ('kg', 'Kilograms (kg)'), ('oz', 'Ounces (oz)'), ('lb', 'Pounds (lb)'), ('piece', 'Piece(s)'), ('can', 'Can(s)'), ('pinch', 'Pinch(es)'), ('clove', 'Clove(s)'), ('head', 'Head(s)')], help_text='Standardized unit of measurement', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipes.category')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_category', to='recipes.recipepage')),
            ],
        ),
    ]
