# Generated by Django 5.2.10 on 2026-06-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_category_remove_recipepage_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='def', max_length=10),
            preserve_default=False,
        ),
    ]
