# Generated by Django 5.2.10 on 2026-07-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_category_description_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='category',
            field=models.CharField(default='Dinner', max_length=50),
        ),
    ]
