# Generated by Django 5.2.10 on 2026-07-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_recipepage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepage',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='protein',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='serving_unit',
            field=models.CharField(blank=True, choices=[('ml', 'Milliliters (ml)'), ('l', 'Liters (l)'), ('tsp', 'Teaspoons (tsp)'), ('tbsp', 'Tablespoons (tbsp)'), ('cup', 'Cups'), ('fl_oz', 'Fluid Ounces (fl oz)'), ('g', 'Grams (g)'), ('mg', 'Milligrams (mg)'), ('mcg', 'Micrograms (mcg)'), ('kg', 'Kilograms (kg)'), ('oz', 'Ounces (oz)'), ('lb', 'Pounds (lb)'), ('piece', 'Piece(s)'), ('can', 'Can(s)'), ('pinch', 'Pinch(es)'), ('clove', 'Clove(s)'), ('head', 'Head(s)')], help_text='Standardized unit of measurement', max_length=20, null=True),
        ),
    ]
