# Generated by Django 5.2.10 on 2026-07-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_remove_recipepage_calories_remove_recipepage_carbs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientnutrientrelationship',
            name='serving_size',
        ),
    ]
