# Generated by Django 5.2.10 on 2026-09-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_remove_ingredientnutrientrelationship_serving_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredientnutrientrelationship',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
