# Generated by Django 5.2.10 on 2026-09-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_alter_ingredient_serving_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(help_text='e.g. All Purpose Flour', max_length=255)),
                ('category', models.CharField(choices=[('flour_powder', 'Flours & Powders'), ('grains_legumes', 'Grains & Legumes'), ('liquids', 'Liquids'), ('sweeteners', 'Sweeteners'), ('nuts_seeds', 'Nuts & Seeds'), ('spices', 'Spices'), ('other', 'Other')], default='other', max_length=50)),
                ('us_quantity', models.DecimalField(decimal_places=2, help_text='US volume amount e.g. 1', max_digits=6)),
                ('us_unit', models.CharField(help_text='US unit e.g. cup, tbsp, tsp', max_length=50)),
                ('metric_quantity', models.DecimalField(decimal_places=2, help_text='Metric amount e.g. 120', max_digits=6)),
                ('metric_unit', models.CharField(choices=[('g', 'Grams'), ('ml', 'Milliliters')], default='g', max_length=10)),
                ('notes', models.CharField(blank=True, help_text='Optional note e.g. sifted, packed, chopped', max_length=255, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Measurement Conversion',
                'verbose_name_plural': 'Measurement Conversions',
                'ordering': ['category', 'sort_order', 'ingredient_name'],
            },
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='serving_size',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='serving_unit',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_liquid',
            field=models.BooleanField(default=False),
        ),
    ]
