# Generated by Django 5.2.10 on 2026-09-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_measurementconversion_remove_ingredient_serving_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'Grams (g)'), ('kg', 'Kilograms (kg)'), ('ml', 'Milliliters (ml)'), ('l', 'Liters (L)'), ('whole', 'Whole'), ('half', 'Half'), ('clove', 'Clove'), ('head', 'Head'), ('stalk', 'Stalk'), ('sprig', 'Sprig'), ('leaf', 'Leaf'), ('slice', 'Slice'), ('piece', 'Piece')], help_text='Standardized unit of measurement', max_length=20, null=True),
        ),
    ]
